"""
Pydantic schemas for the Finance module: unified financial transactions and summaries.
"""

from datetime import date, datetime
from decimal import Decimal
from typing import List, Optional

from pydantic import BaseModel, ConfigDict


# ---------------------------------------------------------------------------
# Financial Transaction
# ---------------------------------------------------------------------------

class FinancialTransactionCreate(BaseModel):
    """
    Schema for creating a financial transaction.

    Note: journal_entry_id is automatically generated by the service layer
    and should not be provided by the client.
    """
    transaction_date: date
    transaction_type: str  # income | expense
    category: Optional[str] = None
    amount: Decimal
    description: Optional[str] = None
    reference_type: Optional[str] = None
    reference_id: Optional[int] = None


class FinancialTransactionResponse(BaseModel):
    """Schema returned when reading a financial transaction."""
    id: int
    transaction_date: date
    transaction_type: str
    category: Optional[str] = None
    amount: Decimal
    description: Optional[str] = None
    reference_type: Optional[str] = None
    reference_id: Optional[int] = None
    journal_entry_id: Optional[int] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Financial Summaries
# ---------------------------------------------------------------------------

class CategorySummary(BaseModel):
    """Summary of transactions by category."""
    category: str
    total_amount: Decimal
    transaction_count: int


class FinancialSummary(BaseModel):
    """Complete financial summary report."""
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    total_income: Decimal
    total_expenses: Decimal
    net_balance: Decimal
    income_by_category: List[CategorySummary]
    expense_by_category: List[CategorySummary]
    transaction_count: int
